const inventario = [
  // ==========================================
  // 1. PROCESADORES (CPU)
  // ==========================================
  {
    id: 1,
    nombre: "Intel Core Ultra 9-285k",
    precio: 14000.0,
    categoria: "cpu",
    destacado: true,
    imagen: "resources/images/productos/1_intel_core_ultra_9.png",
  },
  {
    id: 2,
    nombre: "AMD Ryzen 7 7800X3D",
    precio: 9000.0,
    categoria: "cpu",
    destacado: false,
    imagen: "resources/images/productos/2_amd_ryzen_7_7800x3d.png",
  },
  {
    id: 3,
    nombre: "Intel Core i9-14900K",
    precio: 9699.0,
    categoria: "cpu",
    destacado: true,
    imagen: "resources/images/productos/3_intel_core_i9_14900k.png",
  },
  {
    id: 4,
    nombre: "AMD Ryzen 9 7950X3D",
    precio: 12500.0,
    categoria: "cpu",
    destacado: false,
    imagen: "resources/images/productos/4_amd_ryzen_9_7950x3d.png",
  },
  {
    id: 5,
    nombre: "Intel Core i7-14700K",
    precio: 8200.0,
    categoria: "cpu",
    destacado: false,
    imagen: "resources/images/productos/5_intel_core_i7_14700k.png",
  },
  {
    id: 6,
    nombre: "AMD Ryzen 5 7600X",
    precio: 4500.0,
    categoria: "cpu",
    destacado: false,
    imagen: "resources/images/productos/6_amd_ryzen_5_7600x.png",
  },
  {
    id: 7,
    nombre: "Intel Core i5-13600K",
    precio: 5800.0,
    categoria: "cpu",
    destacado: false,
    imagen: "resources/images/productos/7_intel_core_i5_13600k.png",
  },
  {
    id: 8,
    nombre: "AMD Ryzen 9 7900X",
    precio: 8800.0,
    categoria: "cpu",
    destacado: false,
    imagen: "resources/images/productos/8_amd_ryzen_9_7900x.png",
  },
  {
    id: 9,
    nombre: "Intel Core i5-14400F",
    precio: 3900.0,
    categoria: "cpu",
    destacado: false,
    imagen: "resources/images/productos/9_intel_core_i5_14400f.png",
  },
  {
    id: 10,
    nombre: "AMD Ryzen 7 5700X3D",
    precio: 5200.0,
    categoria: "cpu",
    destacado: false,
    imagen: "resources/images/productos/10_amd_ryzen_7_5700x3d.png",
  },

  // ==========================================
  // 2. TARJETAS GRÁFICAS (GPU)
  // ==========================================
  {
    id: 11,
    nombre: "MSI Gaming GeForce RTX 4090 24GB",
    precio: 40000.0,
    categoria: "gpu",
    destacado: true,
    imagen: "resources/images/productos/11_msi_rtx_4090.png",
  },
  {
    id: 12,
    nombre: "AMD Radeon RX 7900 XTX 24GB",
    precio: 21000.0,
    categoria: "gpu",
    destacado: false,
    imagen: "resources/images/productos/12_amd_rx_7900_xtx.png",
  },
  {
    id: 13,
    nombre: "NVIDIA GeForce RTX 4080 Super 16GB",
    precio: 23000.0,
    categoria: "gpu",
    destacado: true,
    imagen: "resources/images/productos/13_nvidia_rtx_4080_super.png",
  },
  {
    id: 14,
    nombre: "ASUS TUF GeForce RTX 4070 Ti Super",
    precio: 17500.0,
    categoria: "gpu",
    destacado: false,
    imagen: "resources/images/productos/14_asus_tuf_rtx_4070_ti_super.png",
  },
  {
    id: 15,
    nombre: "Gigabyte Radeon RX 7800 XT 16GB",
    precio: 10800.0,
    categoria: "gpu",
    destacado: false,
    imagen: "resources/images/productos/15_gigabyte_rx_7800_xt.png",
  },
  {
    id: 16,
    nombre: "ZOTAC Gaming GeForce RTX 4070 Super",
    precio: 13500.0,
    categoria: "gpu",
    destacado: false,
    imagen: "resources/images/productos/16_zotac_rtx_4070_super.png",
  },
  {
    id: 17,
    nombre: "MSI GeForce RTX 4060 Ti 8GB",
    precio: 8200.0,
    categoria: "gpu",
    destacado: false,
    imagen: "resources/images/productos/17_msi_rtx_4060_ti.png",
  },
  {
    id: 18,
    nombre: "Sapphire Pulse Radeon RX 7600 8GB",
    precio: 5500.0,
    categoria: "gpu",
    destacado: false,
    imagen: "resources/images/productos/18_sapphire_rx_7600.png",
  },
  {
    id: 19,
    nombre: "Intel Arc A770 16GB Limited Edition",
    precio: 6200.0,
    categoria: "gpu",
    destacado: false,
    imagen: "resources/images/productos/19_intel_arc_a770.png",
  },
  {
    id: 20,
    nombre: "PowerColor Radeon RX 7900 XT 20GB",
    precio: 16000.0,
    categoria: "gpu",
    destacado: false,
    imagen: "resources/images/productos/20_powercolor_rx_7900_xt.png",
  },

  // ==========================================
  // 3. TARJETAS MADRE (MOTHERBOARD)
  // ==========================================
  {
    id: 21,
    nombre: "ASUS ROG Strix Z790-E",
    precio: 12000.0,
    categoria: "motherboard",
    destacado: true,
    imagen: "resources/images/productos/21_asus_rog_z790_e.png",
  },
  {
    id: 22,
    nombre: "MSI MAG B650 Tomahawk WiFi",
    precio: 4499.0,
    categoria: "motherboard",
    destacado: false,
    imagen: "resources/images/productos/22_msi_b650_tomahawk.png",
  },
  {
    id: 23,
    nombre: "Gigabyte X670E AORUS Master",
    precio: 9500.0,
    categoria: "motherboard",
    destacado: true,
    imagen: "resources/images/productos/23_gigabyte_x670e_aorus.png",
  },
  {
    id: 24,
    nombre: "ASUS TUF Gaming B650-PLUS",
    precio: 3800.0,
    categoria: "motherboard",
    destacado: false,
    imagen: "resources/images/productos/24_asus_tuf_b650_plus.png",
  },
  {
    id: 25,
    nombre: "ASRock B650E Taichi",
    precio: 8200.0,
    categoria: "motherboard",
    destacado: false,
    imagen: "resources/images/productos/25_asrock_b650e_taichi.png",
  },
  {
    id: 26,
    nombre: "MSI PRO Z790-A WiFi",
    precio: 4900.0,
    categoria: "motherboard",
    destacado: false,
    imagen: "resources/images/productos/26_msi_pro_z790_a.png",
  },
  {
    id: 27,
    nombre: "Gigabyte B760 AORUS ELITE AX",
    precio: 3500.0,
    categoria: "motherboard",
    destacado: false,
    imagen: "resources/images/productos/27_gigabyte_b760_aorus.png",
  },
  {
    id: 28,
    nombre: "ASUS Prime X670-P",
    precio: 5100.0,
    categoria: "motherboard",
    destacado: false,
    imagen: "resources/images/productos/28_asus_prime_x670_p.png",
  },
  {
    id: 29,
    nombre: "ASRock Z790 Steel Legend WiFi",
    precio: 5800.0,
    categoria: "motherboard",
    destacado: false,
    imagen: "resources/images/productos/29_asrock_z790_steel_legend.png",
  },
  {
    id: 30,
    nombre: "NZXT N7 B650E Matte Black",
    precio: 6000.0,
    categoria: "motherboard",
    destacado: false,
    imagen: "resources/images/productos/30_nzxt_n7_b650e.png",
  },

  // ==========================================
  // 4. MEMORIA RAM
  // ==========================================
  {
    id: 31,
    nombre: "Corsair Vengeance 32GB DDR5 6400MHz",
    precio: 9500.0,
    categoria: "ram",
    destacado: true,
    imagen: "resources/images/productos/31_corsair_vengeance_32gb.avif",
  },
  {
    id: 32,
    nombre: "G.Skill Trident Z5 RGB 32GB DDR5 6000MHz",
    precio: 1199.99,
    categoria: "ram",
    destacado: true,
    imagen: "resources/images/productos/32_gskill_trident_z5_32gb.png",
  },
  {
    id: 33,
    nombre: "Kingston FURY Beast 32GB DDR5 5600MHz",
    precio: 2200.0,
    categoria: "ram",
    destacado: false,
    imagen: "resources/images/productos/33_kingston_fury_beast_32gb.png",
  },
  {
    id: 34,
    nombre: "TeamGroup T-Force Delta RGB 32GB DDR5",
    precio: 2400.0,
    categoria: "ram",
    destacado: false,
    imagen: "resources/images/productos/34_teamgroup_delta_32gb.png",
  },
  {
    id: 35,
    nombre: "Crucial Pro 32GB DDR5 5600MHz",
    precio: 1900.0,
    categoria: "ram",
    destacado: false,
    imagen: "resources/images/productos/35_crucial_pro_32gb.png",
  },
  {
    id: 36,
    nombre: "Adata XPG Lancer RGB 32GB DDR5 6000MHz",
    precio: 2500.0,
    categoria: "ram",
    destacado: false,
    imagen: "resources/images/productos/36_adata_xpg_lancer_32gb.png",
  },
  {
    id: 37,
    nombre: "G.Skill Flare X5 32GB DDR5 6000MHz",
    precio: 2300.0,
    categoria: "ram",
    destacado: false,
    imagen: "resources/images/productos/37_gskill_flare_x5_32gb.png",
  },
  {
    id: 38,
    nombre: "Corsair Dominator Titanium 64GB DDR5",
    precio: 22000.0,
    categoria: "ram",
    destacado: false,
    imagen: "resources/images/productos/38_corsair_dominator_64gb.png",
  },
  {
    id: 39,
    nombre: "Kingston FURY Renegade 32GB DDR5 6400MHz",
    precio: 9950.0,
    categoria: "ram",
    destacado: false,
    imagen: "resources/images/productos/39_kingston_fury_renegade_32gb.png",
  },
  {
    id: 40,
    nombre: "Patriot Viper Venom 32GB DDR5 6200MHz",
    precio: 2100.0,
    categoria: "ram",
    destacado: false,
    imagen: "resources/images/productos/40_patriot_viper_venom_32gb.png",
  },

  // ==========================================
  // 5. ALMACENAMIENTO (STORAGE)
  // ==========================================
  {
    id: 41,
    nombre: "Samsung 990 Pro 2TB NVMe",
    precio: 10000.0,
    categoria: "storage",
    destacado: true,
    imagen: "resources/images/productos/41_samsung_990_pro_2tb.webp",
  },
  {
    id: 42,
    nombre: "WD Black SN850X 2TB NVMe",
    precio: 12500.0,
    categoria: "storage",
    destacado: true,
    imagen: "resources/images/productos/42_wd_black_sn850x_2tb.png",
  },
  {
    id: 43,
    nombre: "Crucial T700 2TB Gen5 NVMe",
    precio: 7799.99,
    categoria: "storage",
    destacado: false,
    imagen: "resources/images/productos/43_crucial_t700_2tb.png",
  },
  {
    id: 44,
    nombre: "Kingston KC3000 2TB NVMe",
    precio: 9499.99,
    categoria: "storage",
    destacado: false,
    imagen: "resources/images/productos/44_kingston_kc3000_2tb.png",
  },
  {
    id: 45,
    nombre: "Seagate FireCuda 530 2TB NVMe",
    precio: 9899.99,
    categoria: "storage",
    destacado: false,
    imagen: "resources/images/productos/45_seagate_firecuda_530_2tb.png",
  },
  {
    id: 46,
    nombre: "Corsair MP700 2TB Gen5 NVMe",
    precio: 6999.99,
    categoria: "storage",
    destacado: false,
    imagen: "resources/images/productos/46_corsair_mp700_2tb.png",
  },
  {
    id: 47,
    nombre: "Samsung 980 Pro 1TB NVMe",
    precio: 5700.0,
    categoria: "storage",
    destacado: false,
    imagen: "resources/images/productos/47_samsung_980_pro_1tb.png",
  },
  {
    id: 48,
    nombre: "WD Blue SN580 1TB NVMe",
    precio: 4500.0,
    categoria: "storage",
    destacado: false,
    imagen: "resources/images/productos/48_wd_blue_sn580_1tb.png",
  },
  {
    id: 49,
    nombre: "Crucial P3 Plus 2TB NVMe",
    precio: 7599.99,
    categoria: "storage",
    destacado: false,
    imagen: "resources/images/productos/49_crucial_p3_plus_2tb.png",
  },
  {
    id: 50,
    nombre: "Adata XPG Gammix S70 Blade 2TB",
    precio: 7949.99,
    categoria: "storage",
    destacado: false,
    imagen: "resources/images/productos/50_adata_xpg_gammix_2tb.png",
  },

  // ==========================================
  // 6. FUENTES DE PODER (PSU)
  // ==========================================
  {
    id: 51,
    nombre: "ASUS ROG Strix 1200W Platinum",
    precio: 6000.0,
    categoria: "psu",
    destacado: false,
    imagen: "resources/images/productos/51_asus_rog_1200w.png",
  },
  {
    id: 52,
    nombre: "Corsair RM850x 850W Gold",
    precio: 2600.0,
    categoria: "psu",
    destacado: true,
    imagen: "resources/images/productos/52_corsair_rm850x.png",
  },
  {
    id: 53,
    nombre: "Seasonic Focus GX-1000 1000W Gold",
    precio: 3500.0,
    categoria: "psu",
    destacado: false,
    imagen: "resources/images/productos/53_seasonic_focus_1000w.png",
  },
  {
    id: 54,
    nombre: "EVGA SuperNOVA 850G GT Gold",
    precio: 2400.0,
    categoria: "psu",
    destacado: false,
    imagen: "resources/images/productos/54_evga_supernova_850w.png",
  },
  {
    id: 55,
    nombre: "MSI MPG A1000G PCIE5 1000W Gold",
    precio: 3400.0,
    categoria: "psu",
    destacado: false,
    imagen: "resources/images/productos/55_msi_mpg_a1000g.png",
  },
  {
    id: 56,
    nombre: "Thermaltake Toughpower GF3 1200W",
    precio: 4500.0,
    categoria: "psu",
    destacado: false,
    imagen: "resources/images/productos/56_thermaltake_gf3_1200w.png",
  },
  {
    id: 57,
    nombre: "Be Quiet! Dark Power 13 1000W Titanium",
    precio: 5800.0,
    categoria: "psu",
    destacado: false,
    imagen: "resources/images/productos/57_be_quiet_dark_power_1000w.png",
  },
  {
    id: 58,
    nombre: "Cooler Master MWE Gold 850 V2",
    precio: 2100.0,
    categoria: "psu",
    destacado: false,
    imagen: "resources/images/productos/58_cooler_master_mwe_850w.png",
  },
  {
    id: 59,
    nombre: "XPG Core Reactor 850W Gold",
    precio: 2300.0,
    categoria: "psu",
    destacado: false,
    imagen: "resources/images/productos/59_xpg_core_reactor_850w.png",
  },
  {
    id: 60,
    nombre: "NZXT C1000 Gold 1000W",
    precio: 3200.0,
    categoria: "psu",
    destacado: false,
    imagen: "resources/images/productos/60_nzxt_c1000_1000w.png",
  },

  // ==========================================
  // 7. GABINETES (CASE)
  // ==========================================
  {
    id: 61,
    nombre: "NZXT H9 Flow Blanco",
    precio: 3500.0,
    categoria: "case",
    destacado: true,
    imagen: "resources/images/productos/61_nzxt_h9_flow_blanco.png",
  },
  {
    id: 62,
    nombre: "Corsair 4000D Airflow",
    precio: 1800.0,
    categoria: "case",
    destacado: false,
    imagen: "resources/images/productos/62_corsair_4000d_airflow.png",
  },
  {
    id: 63,
    nombre: "Lian Li O11 Dynamic EVO",
    precio: 3800.0,
    categoria: "case",
    destacado: true,
    imagen: "resources/images/productos/63_lian_li_o11_evo.png",
  },
  {
    id: 64,
    nombre: "Fractal Design North Madera",
    precio: 3200.0,
    categoria: "case",
    destacado: false,
    imagen: "resources/images/productos/64_fractal_north_madera.png",
  },
  {
    id: 65,
    nombre: "Hyte Y60 Panoramic",
    precio: 4000.0,
    categoria: "case",
    destacado: false,
    imagen: "resources/images/productos/65_hyte_y60.png",
  },
  {
    id: 66,
    nombre: "Cooler Master TD500 Mesh",
    precio: 1900.0,
    categoria: "case",
    destacado: false,
    imagen: "resources/images/productos/66_cooler_master_td500.png",
  },
  {
    id: 67,
    nombre: "Phanteks NV7 RGB",
    precio: 4500.0,
    categoria: "case",
    destacado: true,
    imagen: "resources/images/productos/67_phanteks_nv7.png",
  },
  {
    id: 68,
    nombre: "Thermaltake The Tower 500",
    precio: 3000.0,
    categoria: "case",
    destacado: false,
    imagen: "resources/images/productos/68_thermaltake_tower_500.png",
  },
  {
    id: 69,
    nombre: "NZXT H5 Flow",
    precio: 1600.0,
    categoria: "case",
    destacado: false,
    imagen: "resources/images/productos/69_nzxt_h5_flow.png",
  },
  {
    id: 70,
    nombre: "Corsair 5000D Airflow",
    precio: 2800.0,
    categoria: "case",
    destacado: false,
    imagen: "resources/images/productos/70_corsair_5000d_airflow.png",
  },

  // ==========================================
  // 8. MOUSES GAMER
  // ==========================================
  {
    id: 71,
    nombre: "Logitech G Pro X Superlight 2",
    precio: 3000.0,
    categoria: "mouse",
    destacado: true,
    imagen: "resources/images/productos/71_logitech_g_pro_superlight_2.png",
  },
  {
    id: 72,
    nombre: "Razer DeathAdder V3 Pro",
    precio: 2800.0,
    categoria: "mouse",
    destacado: false,
    imagen: "resources/images/productos/72_razer_deathadder_v3.png",
  },
  {
    id: 73,
    nombre: "Logitech G502 Hero",
    precio: 900.0,
    categoria: "mouse",
    destacado: true,
    imagen: "resources/images/productos/73_logitech_g502_hero.png",
  },
  {
    id: 74,
    nombre: "Razer Viper V2 Pro",
    precio: 2600.0,
    categoria: "mouse",
    destacado: false,
    imagen: "resources/images/productos/74_razer_viper_v2.webp",
  },
  {
    id: 75,
    nombre: "Glorious Model O Wireless",
    precio: 1500.0,
    categoria: "mouse",
    destacado: false,
    imagen: "resources/images/productos/75_glorious_model_o.png",
  },
  {
    id: 76,
    nombre: "SteelSeries Aerox 3",
    precio: 1200.0,
    categoria: "mouse",
    destacado: false,
    imagen: "resources/images/productos/76_steelseries_aerox_3.png",
  },
  {
    id: 77,
    nombre: "Corsair Dark Core RGB Pro",
    precio: 1700.0,
    categoria: "mouse",
    destacado: false,
    imagen: "resources/images/productos/77_corsair_dark_core.avif",
  },
  {
    id: 78,
    nombre: "HyperX Pulsefire Haste",
    precio: 800.0,
    categoria: "mouse",
    destacado: false,
    imagen: "resources/images/productos/78_hyperx_pulsefire.png",
  },
  {
    id: 79,
    nombre: "Zowie EC2-C E-Sports",
    precio: 1400.0,
    categoria: "mouse",
    destacado: false,
    imagen: "resources/images/productos/79_zowie_ec2_c.avif",
  },
  {
    id: 80,
    nombre: "Razer Basilisk V3",
    precio: 1100.0,
    categoria: "mouse",
    destacado: false,
    imagen: "resources/images/productos/80_razer_basilisk_v3.png",
  },

  // ==========================================
  // 9. TECLADOS
  // ==========================================
  {
    id: 81,
    nombre: "Wooting 60HE Analógico",
    precio: 4000.0,
    categoria: "keyboard",
    destacado: true,
    imagen: "resources/images/productos/81_wooting_60he.png",
  },
  {
    id: 82,
    nombre: "Logitech G915 TKL Wireless",
    precio: 3500.0,
    categoria: "keyboard",
    destacado: true,
    imagen: "resources/images/productos/82_logitech_g915_tkl.png",
  },
  {
    id: 83,
    nombre: "Razer Huntsman V3 Pro",
    precio: 4500.0,
    categoria: "keyboard",
    destacado: false,
    imagen: "resources/images/productos/83_razer_huntsman_v3.png",
  },
  {
    id: 84,
    nombre: "Corsair K70 RGB PRO",
    precio: 3000.0,
    categoria: "keyboard",
    destacado: false,
    imagen: "resources/images/productos/84_corsair_k70_pro.avif",
  },
  {
    id: 85,
    nombre: "Keychron Q1 Pro Custom",
    precio: 3800.0,
    categoria: "keyboard",
    destacado: true,
    imagen: "resources/images/productos/85_keychron_q1_pro.png",
  },
  {
    id: 86,
    nombre: "SteelSeries Apex Pro TKL",
    precio: 3600.0,
    categoria: "keyboard",
    destacado: false,
    imagen: "resources/images/productos/86_steelseries_apex_pro.png",
  },
  {
    id: 87,
    nombre: "HyperX Alloy Origins Core",
    precio: 1800.0,
    categoria: "keyboard",
    destacado: false,
    imagen: "resources/images/productos/87_hyperx_alloy_origins.png",
  },
  {
    id: 88,
    nombre: "Razer BlackWidow V4",
    precio: 3200.0,
    categoria: "keyboard",
    destacado: false,
    imagen: "resources/images/productos/88_razer_blackwidow_v4.png",
  },
  {
    id: 89,
    nombre: "Ducky One 3 Mini",
    precio: 2500.0,
    categoria: "keyboard",
    destacado: false,
    imagen: "resources/images/productos/89_ducky_one_3_mini.png",
  },
  {
    id: 90,
    nombre: "Logitech G Pro X TKL",
    precio: 3400.0,
    categoria: "keyboard",
    destacado: false,
    imagen: "resources/images/productos/90_logitech_g_pro_tkl.webp",
  },

  // ==========================================
  // 10. MICRÓFONOS
  // ==========================================
  {
    id: 91,
    nombre: "Shure SM7B",
    precio: 8000.0,
    categoria: "mic",
    destacado: true,
    imagen: "resources/images/productos/91_shure_sm7b.png",
  },
  {
    id: 92,
    nombre: "HyperX QuadCast S RGB",
    precio: 2800.0,
    categoria: "mic",
    destacado: true,
    imagen: "resources/images/productos/92_hyperx_quadcast_s.png",
  },
  {
    id: 93,
    nombre: "Elgato Wave:3",
    precio: 3000.0,
    categoria: "mic",
    destacado: false,
    imagen: "resources/images/productos/93_elgato_wave_3.png",
  },
  {
    id: 94,
    nombre: "Blue Yeti X Professional",
    precio: 3200.0,
    categoria: "mic",
    destacado: false,
    imagen: "resources/images/productos/94_blue_yeti_x.png",
  },
  {
    id: 95,
    nombre: "Razer Seiren Mini",
    precio: 1000.0,
    categoria: "mic",
    destacado: false,
    imagen: "resources/images/productos/95_razer_seiren_mini.png",
  },
  {
    id: 96,
    nombre: "Audio-Technica AT2020USB+",
    precio: 2500.0,
    categoria: "mic",
    destacado: true,
    imagen: "resources/images/productos/96_audio_technica_at2020.png",
  },
  {
    id: 97,
    nombre: "Rode PodMic",
    precio: 2000.0,
    categoria: "mic",
    destacado: false,
    imagen: "resources/images/productos/97_rode_podmic.png",
  },
  {
    id: 98,
    nombre: "Logitech Yeti GX",
    precio: 2600.0,
    categoria: "mic",
    destacado: false,
    imagen: "resources/images/productos/98_logitech_yeti_gx.png",
  },
  {
    id: 99,
    nombre: "Fifine AmpliGame A8",
    precio: 900.0,
    categoria: "mic",
    destacado: false,
    imagen: "resources/images/productos/99_fifine_a8.png",
  },
  {
    id: 100,
    nombre: "SteelSeries Alias",
    precio: 3500.0,
    categoria: "mic",
    destacado: false,
    imagen: "resources/images/productos/100_steelseries_alias.png",
  },

  // ==========================================
  // 11. EXTRAS / ACCESORIOS
  // ==========================================
  {
    id: 101,
    nombre: 'Monitor ASUS ROG Swift OLED 27"',
    precio: 18000.0,
    categoria: "accessory",
    destacado: true,
    imagen: "resources/images/productos/101_asus_rog_oled_27.png",
  },
  {
    id: 102,
    nombre: 'Monitor LG UltraGear 27" 165Hz',
    precio: 6000.0,
    categoria: "accessory",
    destacado: false,
    imagen: "resources/images/productos/102_lg_ultragear_27.png",
  },
  {
    id: 103,
    nombre: "Audífonos HyperX Cloud III",
    precio: 3000.0,
    categoria: "accessory",
    destacado: true,
    imagen: "resources/images/productos/103_hyperx_cloud_3.png",
  },
  {
    id: 104,
    nombre: "Audífonos Logitech G733 RGB",
    precio: 2500.0,
    categoria: "accessory",
    destacado: false,
    imagen: "resources/images/productos/104_logitech_g733.png",
  },
  {
    id: 105,
    nombre: "Webcam Elgato Facecam 1080p60",
    precio: 3000.0,
    categoria: "accessory",
    destacado: false,
    imagen: "resources/images/productos/105_elgato_facecam.png",
  },
  {
    id: 106,
    nombre: "Webcam Logitech C920s HD",
    precio: 1200.0,
    categoria: "accessory",
    destacado: false,
    imagen: "resources/images/productos/106_logitech_c920s.png",
  },
  {
    id: 107,
    nombre: "Capturadora Elgato HD60 X",
    precio: 3500.0,
    categoria: "accessory",
    destacado: true,
    imagen: "resources/images/productos/107_elgato_hd60x.png",
  },
  {
    id: 108,
    nombre: "Stream Deck Elgato MK.2",
    precio: 3000.0,
    categoria: "accessory",
    destacado: true,
    imagen: "resources/images/productos/108_elgato_stream_deck.png",
  },
  {
    id: 109,
    nombre: "Silla Gamer Secretlab Titan Evo",
    precio: 10000.0,
    categoria: "accessory",
    destacado: false,
    imagen: "resources/images/productos/109_secretlab_titan_evo.png",
  },
  {
    id: 110,
    nombre: "Mousepad Corsair MM700 RGB",
    precio: 1200.0,
    categoria: "accessory",
    destacado: false,
    imagen: "resources/images/productos/110_corsair_mm700_rgb.png",
  },
];
